#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER learn_pg_jihye SUPERUSER PASSWORD 'pass123'"
echo "Created Postgres user 'learn_pg_jihye'"

psql -q -c "CREATE DATABASE learn_pg__ WITH OWNER learn_pg_jihye"
echo "Created Postgres database 'learn_pg__'"

cp example.env .env
echo "Created .env containing DATABASE_URL"